[package]
name = "imflow"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["debug", "canvas", "tokio", "image"]}
image = "0.25.6"

itertools = "0.12"
memmap2 = "0.9.5"
# rustc-hash.workspace = true
tokio = { version = "1.44.1", features = ["sync"] }
tracing-subscriber = "0.3"
zune-image = {version = "0.4.15", features = ["all"]}
[profile.dev.package.zune-jpeg]
opt-level = 3
